name: dart_osmpbf
description: A parser for the OpenStreetMap PBF format.
version: 0.0.1
repository: https://github.com/joranmulderij/dart_osmpbf

environment:
  sdk: ^3.4.4

dependencies:
  archive: ^3.6.1
  fixnum: ^1.1.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
